fix: transfer serialized parallel data via file
Error: parallel jobs didn't work anymore
Resolved by: transferring TaskSet data via a serialized file instead of a serialized argument string